// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/alex-storchak/shortener/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAPIShortenProcessor creates a new instance of MockAPIShortenProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIShortenProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIShortenProcessor {
	mock := &MockAPIShortenProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAPIShortenProcessor is an autogenerated mock type for the APIShortenProcessor type
type MockAPIShortenProcessor struct {
	mock.Mock
}

type MockAPIShortenProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIShortenProcessor) EXPECT() *MockAPIShortenProcessor_Expecter {
	return &MockAPIShortenProcessor_Expecter{mock: &_m.Mock}
}

// Process provides a mock function for the type MockAPIShortenProcessor
func (_mock *MockAPIShortenProcessor) Process(ctx context.Context, req model.ShortenRequest) (*model.ShortenResponse, string, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 *model.ShortenResponse
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ShortenRequest) (*model.ShortenResponse, string, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ShortenRequest) *model.ShortenResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ShortenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.ShortenRequest) string); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, model.ShortenRequest) error); ok {
		r2 = returnFunc(ctx, req)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAPIShortenProcessor_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type MockAPIShortenProcessor_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - ctx context.Context
//   - req model.ShortenRequest
func (_e *MockAPIShortenProcessor_Expecter) Process(ctx interface{}, req interface{}) *MockAPIShortenProcessor_Process_Call {
	return &MockAPIShortenProcessor_Process_Call{Call: _e.mock.On("Process", ctx, req)}
}

func (_c *MockAPIShortenProcessor_Process_Call) Run(run func(ctx context.Context, req model.ShortenRequest)) *MockAPIShortenProcessor_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.ShortenRequest
		if args[1] != nil {
			arg1 = args[1].(model.ShortenRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIShortenProcessor_Process_Call) Return(shortenResponse *model.ShortenResponse, s string, err error) *MockAPIShortenProcessor_Process_Call {
	_c.Call.Return(shortenResponse, s, err)
	return _c
}

func (_c *MockAPIShortenProcessor_Process_Call) RunAndReturn(run func(ctx context.Context, req model.ShortenRequest) (*model.ShortenResponse, string, error)) *MockAPIShortenProcessor_Process_Call {
	_c.Call.Return(run)
	return _c
}
