services:
  db:
    image: postgres:16-bookworm
    restart: always
    environment:
      POSTGRES_PASSWORD: StrongPassword01
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - "54320:5432"