.PHONY: help
.PHONY: generate-mocks test test-static generate-reset generate-proto
.PHONY: build
.PHONY: generate
.PHONY: clean clean-bin clean-mocks clean-easyjson clean-reset
.PHONY: format
.PHONY: doc

BUILD_VCS ?= true
GODOC_PORT ?= 8081

COMMIT := $(shell git rev-parse HEAD)
DATE := $(shell date -u +%Y-%m-%dT%H:%M:%SZ)
VERSION := $(shell git describe --tags --exact-match 2>/dev/null || echo dev)

ldflags = -X main.buildVersion=$(VERSION) -X main.buildDate=$(DATE) -X main.buildCommit=$(COMMIT)

format:
	find . -type f -name '*.go' \
		-not -name '*_easyjson.go' \
		-not -name '*.pb.go' \
		-not -path '*/mocks/*' \
		-exec goimports -local "github.com/alex-storchak/shortener" -w {} \;


doc:
	godoc -http=":$(GODOC_PORT)"

build: generate generate-mocks
	cd cmd/shortener && go build -ldflags "$(ldflags)" -buildvcs=$(BUILD_VCS) -o shortener

generate-mocks:
	mockery

generate-reset:
	go run ./cmd/reset

generate-proto:
	@protoc -I . \
		--go_out=. \
		--go_opt=paths=source_relative \
		--go-grpc_out=. \
		--go-grpc_opt=paths=source_relative \
		--go_opt=default_api_level=API_OPAQUE \
		api/proto/shortener/shortener.proto

generate: generate-mocks generate-reset generate-proto
	go generate ./...

clean-mocks:
	@echo "Removing generated mocks..."
	# Находим каталоги 'mocks' и удаляем mock_*.go внутри
	@find . -type d -name mocks -prune -exec sh -c ' \
		for d; do \
			find "$$d" -maxdepth 1 -type f -name "mock_*.go" -print -delete; \
			rmdir "$$d" 2>/dev/null || true; \
		done' sh {} +
	@echo "Done."

clean-easyjson:
	@echo "Removing generated easyjson files..."
	@find . -type f -name "*_easyjson.go" -print -delete
	@echo "Done."

clean-reset:
	find . -type f -name "reset.gen.go" -delete


clean-proto:
	@find api/proto -name "*.pb.go" -type f -print -delete

clean-bin:
	rm -f cmd/shortener/shortener

clean: clean-mocks clean-easyjson clean-bin clean-reset

test: generate-mocks
	go test ./...

test-static: generate-mocks
	go vet -vettool=$(which statictest) ./...

test-shortener: build
	./autotest/run_all.sh

help:
	@echo ""
	@echo "Usage: make <target>"
	@echo "  make test-shortener"
	@echo ""
	@echo "Targets:"
	@echo "  doc                Run godoc server. Default port: $(GODOC_PORT)"
	@echo ""
	@echo "  format             Format code with goimports. Excluded files: mockery mocks, easyjson"
	@echo ""
	@echo "  build              Build shortener binary"
	@echo ""
	@echo "  generate           Go generate"
	@echo ""
	@echo "  generate-mocks     Generate mocks for interfaces"
	@echo "  generate-reset     Generate reset methods for structs marked with generate:reset"
	@echo "  generate-proto     Generate proto files"
	@echo ""
	@echo "  clean              Clean up mocks and binary"
	@echo "  clean-mocks        Clean up mocks"
	@echo "  clean-easyjson     Clean up easyjson files"
	@echo "  clean-reset        Clean up reset.gen.go files (generated by ./cmd/reset/main.go)"
	@echo "  clean-proto        Clean up go code generated from proto files"
	@echo ""
	@echo "  clean-bin          Clean up binary"
	@echo ""
	@echo "  test               Run all tests"
	@echo "  test-static        Run required autotest statictest (binary file \"statictest\" must be available from PATH)"
	@echo "  test-shortener     Run required autotest shortenertest (requires binary \"./autotest/run_all.sh\" script that not present in repo)"
	@echo ""