BEGIN;

CREATE TABLE IF NOT EXISTS auth_user (
    id         INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user_uuid  VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT NOW()
);

COMMIT;