// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/alex-storchak/shortener/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuditEventPublisher creates a new instance of MockAuditEventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditEventPublisher {
	mock := &MockAuditEventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuditEventPublisher is an autogenerated mock type for the AuditEventPublisher type
type MockAuditEventPublisher struct {
	mock.Mock
}

type MockAuditEventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditEventPublisher) EXPECT() *MockAuditEventPublisher_Expecter {
	return &MockAuditEventPublisher_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type MockAuditEventPublisher
func (_mock *MockAuditEventPublisher) Publish(event model.AuditEvent) {
	_mock.Called(event)
	return
}

// MockAuditEventPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockAuditEventPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - event model.AuditEvent
func (_e *MockAuditEventPublisher_Expecter) Publish(event interface{}) *MockAuditEventPublisher_Publish_Call {
	return &MockAuditEventPublisher_Publish_Call{Call: _e.mock.On("Publish", event)}
}

func (_c *MockAuditEventPublisher_Publish_Call) Run(run func(event model.AuditEvent)) *MockAuditEventPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.AuditEvent
		if args[0] != nil {
			arg0 = args[0].(model.AuditEvent)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuditEventPublisher_Publish_Call) Return() *MockAuditEventPublisher_Publish_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAuditEventPublisher_Publish_Call) RunAndReturn(run func(event model.AuditEvent)) *MockAuditEventPublisher_Publish_Call {
	_c.Run(run)
	return _c
}
