// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockShortURLBuilder creates a new instance of MockShortURLBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShortURLBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShortURLBuilder {
	mock := &MockShortURLBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShortURLBuilder is an autogenerated mock type for the ShortURLBuilder type
type MockShortURLBuilder struct {
	mock.Mock
}

type MockShortURLBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShortURLBuilder) EXPECT() *MockShortURLBuilder_Expecter {
	return &MockShortURLBuilder_Expecter{mock: &_m.Mock}
}

// Build provides a mock function for the type MockShortURLBuilder
func (_mock *MockShortURLBuilder) Build(shortID string) string {
	ret := _mock.Called(shortID)

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(shortID)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockShortURLBuilder_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type MockShortURLBuilder_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
//   - shortID string
func (_e *MockShortURLBuilder_Expecter) Build(shortID interface{}) *MockShortURLBuilder_Build_Call {
	return &MockShortURLBuilder_Build_Call{Call: _e.mock.On("Build", shortID)}
}

func (_c *MockShortURLBuilder_Build_Call) Run(run func(shortID string)) *MockShortURLBuilder_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockShortURLBuilder_Build_Call) Return(s string) *MockShortURLBuilder_Build_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockShortURLBuilder_Build_Call) RunAndReturn(run func(shortID string) string) *MockShortURLBuilder_Build_Call {
	_c.Call.Return(run)
	return _c
}
